inherit_from: .rubocop_hound.yml

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - 'config/environments/*'

Rails/I18nLocaleTexts:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/dev_data_builder.rb'

RSpec/IndexedLet:
  Enabled: false

