inherit_from: .rubocop_hound.yml

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/20240817192951_create_active_storage_tables.active_storage.rb'

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - 'config/environments/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20240817192951_create_active_storage_tables.active_storage.rb'

Rails/I18nLocaleTexts:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/data_builder.rb'
    - 'app/models/budget_importer.rb'

RSpec/IndexedLet:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false
